# Generated by Django 4.0 on 2023-11-24 22:38

import commons.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=commons.utility.upload_image_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=commons.utility.upload_file_path),
        ),
    ]
