# Generated by Django 4.0 on 2023-11-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('tasks', models.CharField(max_length=512, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='changed_by',
        ),
        migrations.AddField(
            model_name='task',
            name='allow_time_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='autidors',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskworklog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(max_length=512, null=True)),
                ('field', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.crmmember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
