# Generated by Django 4.0 on 2023-11-23 19:20

import commons.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_taskcolumn_rename_owner_task_changed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ref_number', models.IntegerField(blank=True, null=True)),
                ('ref_date', models.DateTimeField(blank=True, null=True)),
                ('data_action', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='crmproject',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=commons.utility.upload_image_path),
        ),
        migrations.AlterField(
            model_name='taskactivitydocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=commons.utility.upload_file_path),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=commons.utility.upload_file_path),
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=commons.utility.upload_file_path),
        ),
        migrations.CreateModel(
            name='ClientActivityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=commons.utility.upload_file_path)),
                ('client_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.clientactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientActivityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('client_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.clientactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='action_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.clientactivitytype'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
